name: Bundle Analysis

on:
  pull_request:
    branches: [main, develop]
    paths:
      - "components/**"
      - "lib/**"
      - "app/**"
      - "pages/**"
      - "next.config.ts"
      - "package.json"
      - "package-lock.json"
  push:
    branches: [main]
    paths:
      - "components/**"
      - "lib/**"
      - "app/**"
      - "pages/**"
      - "next.config.ts"
      - "package.json"
      - "package-lock.json"

jobs:
  bundle-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Download previous bundle analysis
        uses: actions/download-artifact@v4
        with:
          name: bundle-analysis
          path: reports/
        continue-on-error: true

      - name: Backup previous report
        run: |
          if [ -f reports/bundle-analysis.json ]; then
            cp reports/bundle-analysis.json reports/bundle-analysis-previous.json
          fi
        continue-on-error: true

      - name: Run bundle analysis
        run: node scripts/bundle-analysis.js analyze
        env:
          NODE_ENV: production

      - name: Check for bundle size regression
        id: regression-check
        run: |
          if node scripts/bundle-analysis.js check-regression; then
            echo "regression=false" >> $GITHUB_OUTPUT
          else
            echo "regression=true" >> $GITHUB_OUTPUT
          fi
        continue-on-error: true

      - name: Upload bundle analysis results
        uses: actions/upload-artifact@v4
        with:
          name: bundle-analysis
          path: |
            reports/bundle-analysis.json
            reports/bundle-analysis.md
            analyze/
          retention-days: 30

      - name: Comment PR with bundle analysis
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const path = require('path');

            try {
              const reportPath = path.join(process.cwd(), 'reports', 'bundle-analysis.md');
              const report = fs.readFileSync(reportPath, 'utf8');
              
              const { data: comments } = await github.rest.issues.listComments({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
              });
              
              const botComment = comments.find(comment => 
                comment.user.type === 'Bot' && 
                comment.body.includes('Bundle Analysis Report')
              );
              
              const commentBody = `## 📦 Bundle Analysis Report
              
              ${report}
              
              ${steps.regression-check.outputs.regression === 'true' ? 
                '⚠️ **Bundle size regression detected!** Please review the changes.' : 
                '✅ No significant bundle size regression detected.'
              }
              
              <details>
              <summary>View detailed analysis</summary>
              
              You can download the full analysis report from the workflow artifacts.
              
              </details>`;
              
              if (botComment) {
                await github.rest.issues.updateComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  comment_id: botComment.id,
                  body: commentBody
                });
              } else {
                await github.rest.issues.createComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: context.issue.number,
                  body: commentBody
                });
              }
            } catch (error) {
              console.error('Failed to post comment:', error);
            }

      - name: Fail on bundle size regression
        if: steps.regression-check.outputs.regression == 'true' && github.event_name == 'pull_request'
        run: |
          echo "❌ Bundle size regression detected. Please optimize your changes."
          exit 1

      - name: Generate bundle size badge
        if: github.ref == 'refs/heads/main'
        run: |
          # Extract total size from report
          TOTAL_SIZE=$(node -e "
            const report = require('./reports/bundle-analysis.json');
            const { formatBytes } = require('./scripts/bundle-analysis.js');
            console.log(formatBytes(report.totalSize));
          ")

          # Create badge data
          mkdir -p badges
          echo "{\"schemaVersion\": 1, \"label\": \"bundle size\", \"message\": \"$TOTAL_SIZE\", \"color\": \"blue\"}" > badges/bundle-size.json

      - name: Upload badge data
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: bundle-size-badge
          path: badges/bundle-size.json
          retention-days: 1
